In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
from sklearn.preprocessing import PolynomialFeatures, StandardScaler, FunctionTransformer, OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer

In [55]:
train = pd.read_csv(r'C:\Users\Abhay\Downloads\Train.csv')

In [56]:
test = pd.read_csv(r'C:\Users\Abhay\Downloads\Test.csv')

In [57]:
train.head(5)

   Unnamed: 0                                                url  Phish?
0           0  www.musik-glanzmann.ch/product-page/paiste-sig...       0
1           1                            kinkydangle.blogspot.ae       1
2           2                     fukuchan.net/publics/index/32/       0
3           3                      gaypornstorage.blogspot.co.at       1
4           4  herecomestheguide.com/southern-california/wedd...       1

In [65]:
test = test.fillna(0)

In [59]:
### Removing the Unnamed Column from both the dataset Train and Test
train = train.drop('Unnamed: 0', axis = 1)
test = test.drop('Unnamed: 0', axis = 1)

In [ ]:
train.sample(5)

In [70]:
train.isnull().sum()

url       0
Phish?    0
dtype: int64

In [71]:
test.isnull().sum()

url       0
Phish?    0
dtype: int64

In [93]:
from urllib.parse import urlparse

def extract_length_features(url):
    parsed = urlparse(url)
    features = {}
    # Full URL length
    features['url_length'] = len(url)
    # Domain length
    features['domain_length'] = len(parsed.netloc)
    # Path length
    features['path_length'] = len(parsed.path)
    # Query length
    features['query_length'] = len(parsed.query)
    # Number of subdomains
    features['subdomain_count'] = parsed.netloc.count('.')
    return pd.Series(features)

length_features = train['url'].apply(extract_length_features)
df = pd.concat([train, length_features], axis=1)

In [ ]:
df

,url,Phish?,url_length,domain_length,path_length,query_length,subdomain_count
0,www.musik-glanzmann.ch/product-page/paiste-sig...,0,67,0,67,0,0
1,kinkydangle.blogspot.ae,1,23,0,23,0,0
2,fukuchan.net/publics/index/32/,0,30,0,30,0,0
3,gaypornstorage.blogspot.co.at,1,29,0,29,0,0
4,herecomestheguide.com/southern-california/wedd...,1,94,0,94,0,0
...,...,...,...,...,...,...,...
3999995,hakusakublog.blog86.fc2.com/blog-entry-531.html,0,47,0,47,0,0
3999996,www.xyzscripts.com,1,18,0,18,0,0
3999997,cumandgetit.blogspot.al,1,23,0,23,0,0
3999998,www.sbdmtr.cz/index.php?option=com_content&vie...,0,71,0,23,47,0
3999999,opac.sbn.it/opacsbn/opaclib?rpnlabel=+bid+%3d+...,0,405,0,27,377,0

In [95]:
df['domain_length'].unique()

array([ 0, 13, 16, 15, 18, 14, 46,  7])