In [1]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv('Train2.csv')

In [10]:
df.head(5)

                                                 url  Phish?
0               http://elretohistorico.com/tag/bruja       0
1      http://fcouncil.ncku.edu.tw/ebsmeeting_1.aspx       0
2                               http://q-r.to/bg6qsB       1
3  http://www.polaroid-passion.com/forum/viewforu...       0
4  http://docs.google.com/presentation/d/e/2PACX-...       1

In [11]:
df.shape

(111401, 2)

In [63]:
df1 = pd.read_csv('Train.csv')

In [64]:
df1['url'].dtype

dtype('O')

In [65]:
df1 = df1.drop(['Unnamed: 0'], axis = 1)

In [66]:
df1['url'] = 'http://' + df1['url'].astype(str)
df1

                                                       url  Phish?
0        http://www.musik-glanzmann.ch/product-page/pai...       0
1                           http://kinkydangle.blogspot.ae       1
2                    http://fukuchan.net/publics/index/32/       0
3                     http://gaypornstorage.blogspot.co.at       1
4        http://herecomestheguide.com/southern-californ...       1
...                                                    ...     ...
3999995  http://hakusakublog.blog86.fc2.com/blog-entry-...       0
3999996                          http://www.xyzscripts.com       1
3999997                     http://cumandgetit.blogspot.al       1
3999998  http://www.sbdmtr.cz/index.php?option=com_cont...       0
3999999  http://opac.sbn.it/opacsbn/opaclib?rpnlabel=+b...       0

[4000000 rows x 2 columns]

In [67]:
phish = df1[df1['Phish?'] == 1].sample(56000)

In [68]:
phish

                                             url  Phish?
348076   http://monica-bellucci-2013.blogspot.is       1
2938830             http://bluefp.ps.netease.com       1
769120                 http://my-gay.blogspot.qa       1
2187927                     http://binichsexy.de       1
16860               http://casastoneworks.com.au       1
...                                          ...     ...
2656694         http://baise-roubaix.blogspot.am       1
1779862                http://1010data.slack.com       1
1743711       http://emily-sweet-pic.blogspot.my       1
2114584                http://sextoystore.com.au       1
3218009                    http://dominatrice.hu       1

[56000 rows x 2 columns]

In [69]:
leg = df1[~df1['url'].isin(df['url'])]

In [72]:
leg = leg[leg['Phish?'] == 0]

In [74]:
leg = leg.sample(54000)

In [75]:
leg

                                                       url  Phish?
3625606  http://kisj.moskva-rynok.ru/teen-dating-ideas-...       0
1654110  http://bh-region.ru/shop_by_price.php?range=0&...       0
4428     http://www.golfchannel.com/article/golftalkcen...       0
3692746  http://assistirporno.xxx/porno/amador/negao-co...       0
1199870  http://articles.latimes.com/1990-12-04/news/wr...       0
...                                                    ...     ...
1655354  http://www.onlinecarstereo.com/all/products/15...       0
64919    http://kalach.cveti-buketi.ru/product/buket-ts...       0
3161547  http://vuitton2009.blog93.fc2.com/blog-categor...       0
3922600  http://theevilchef.blogspot.com/2011/12/oys-wi...       0
2205307  http://www.suiteness.com/suites/united-states/...       0

[54000 rows x 2 columns]

In [78]:
merge = pd.concat([phish, leg], axis = 0)

In [80]:
merge = merge.sample(frac = 1).reset_index(drop = True)

In [81]:
merge

                                                      url  Phish?
0              http://tylerdonnelly.blogspot.com/2014/01/       0
1                             http://topsecretrecipes.com       1
2                                  http://andersmanga.com       1
3       http://pdalife.ru/dog-simulator1-android-a1278...       0
4       http://www.dltk-teach.com/t.asp?t=http://www.d...       0
...                                                   ...     ...
109995  http://maison-quatre.com/2016/10/17/le-pont-de...       0
109996                  http://rcgwpro1.support.ricoh.com       1
109997                                 http://mxp2075.com       1
109998  http://trappedtextiles.blogspot.com/2011/03/ve...       0
109999           http://www.rocr.net/index.php?p=20050228       0

[110000 rows x 2 columns]

In [82]:
final = pd.concat([df, merge], axis = 0)

In [83]:
final

                                                      url  Phish?
0                    http://elretohistorico.com/tag/bruja       0
1           http://fcouncil.ncku.edu.tw/ebsmeeting_1.aspx       0
2                                    http://q-r.to/bg6qsB       1
3       http://www.polaroid-passion.com/forum/viewforu...       0
4       http://docs.google.com/presentation/d/e/2PACX-...       1
...                                                   ...     ...
109995  http://maison-quatre.com/2016/10/17/le-pont-de...       0
109996                  http://rcgwpro1.support.ricoh.com       1
109997                                 http://mxp2075.com       1
109998  http://trappedtextiles.blogspot.com/2011/03/ve...       0
109999           http://www.rocr.net/index.php?p=20050228       0

[221401 rows x 2 columns]

In [84]:
final = final.sample(frac = 1).reset_index(drop = True)

In [85]:
final.shape

(221401, 2)

In [86]:
final.to_csv('Final_Train.csv')

In [87]:
! git status

On branch Abhay
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ../Data_Fetching.ipynb
	modified:   SVM.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	../.ipynb_checkpoints/
	.ipynb_checkpoints/Final_Train-checkpoint.ipynb
	.ipynb_checkpoints/Moksh_testing-checkpoint.csv
	.ipynb_checkpoints/Train2-checkpoint.csv
	.ipynb_checkpoints/Train3-checkpoint.csv
	Final_Train.csv
	Final_Train.ipynb
	Test.csv
	Train.csv

no changes added to commit (use "git add" and/or "git commit -a")

In [88]:
! git add .

warning: in the working copy of 'ML/SVM.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'ML/.ipynb_checkpoints/Final_Train-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'ML/.ipynb_checkpoints/Train2-checkpoint.csv', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'ML/Final_Train.ipynb', LF will be replaced by CRLF the next time Git touches it

In [89]:
! git commit -m'Final_Merge_TrainDataset_created'

[Abhay 81a26ae] 'Final_Merge_TrainDataset_created'
 9 files changed, 7063408 insertions(+), 1 deletion(-)
 create mode 100644 ML/.ipynb_checkpoints/Final_Train-checkpoint.ipynb
 create mode 100644 ML/.ipynb_checkpoints/Moksh_testing-checkpoint.csv
 create mode 100644 ML/.ipynb_checkpoints/Train2-checkpoint.csv
 create mode 100644 ML/.ipynb_checkpoints/Train3-checkpoint.csv
 create mode 100644 ML/Final_Train.csv
 create mode 100644 ML/Final_Train.ipynb
 create mode 100644 ML/Test.csv
 create mode 100644 ML/Train.csv