In [1]:
import pandas as pd
import numpy as np

In [48]:
df1 = pd.read_csv('Test_process.csv')
df1

         Unnamed: 0                                                url  Phish?
0                 0  www.mailexperiences.co.uk/fly-fishing-for-two-...       0
1                 1                       tvservice.org/diagrams/akura       0
2                 2                            ebonychicks.blogspot.ch       1
3                 3      kyokukenzo.blog13.fc2.com/blog-entry-735.html       0
4                 4  cdm.csbsju.edu/digital/collection/hmmlclrmicr/...       0
...             ...                                                ...     ...
2568179     2568179                                             3cx.de       1
2568180     2568180  loing-ma.com/ucp.php?mode=login&sid=616d66ebfd...       0
2568181     2568181                                         ltmagox.ru       1
2568182     2568182                      morgane-clara.blogspot.com.es       1
2568183     2568183                        spankersview.blogspot.co.za       1

[2568184 rows x 3 columns]

In [49]:
df2 = pd.read_csv('PhishTank.csv')
df2

       Unnamed: 0                                                url  Phish?
0               0            http://allegro.pl8475rezerwacja6897.sbs       1
1               1                  http://allegro.pl-oferta85329.cfd       1
2               2        http://allegrolokalnie.pl-oferta-198032.cfd       1
3               3  http://allegrolokalnie.pl-oferta-id-184566-kat...       1
4               4  http://allegrolokalnie.pl-kategorie-id-192382.sbs       1
...           ...                                                ...     ...
56337       56337              http://webmailadmin0.myfreesites.net/       1
56338       56338  http://www.formbuddy.com/cgi-bin/formdisp.pl?u...       1
56339       56339  http://www.formbuddy.com/cgi-bin/formdisp.pl?u...       1
56340       56340       http://www.habbocreditosparati.blogspot.com/       1
56341       56341  http://creditiperhabbogratissicuro100.blogspot...       1

[56342 rows x 3 columns]

In [50]:
df2 = df2.drop(['Unnamed: 0'], axis = 1)
df1 = df1.drop(['Unnamed: 0'], axis = 1)

In [51]:
df1[df1['Phish?'] == 1].shape

(1480467, 2)

In [52]:
df1['url'] = 'http://' + df1['url'].astype(str)
df1

                                                       url  Phish?
0        http://www.mailexperiences.co.uk/fly-fishing-f...       0
1                      http://tvservice.org/diagrams/akura       0
2                           http://ebonychicks.blogspot.ch       1
3        http://kyokukenzo.blog13.fc2.com/blog-entry-73...       0
4        http://cdm.csbsju.edu/digital/collection/hmmlc...       0
...                                                    ...     ...
2568179                                      http://3cx.de       1
2568180  http://loing-ma.com/ucp.php?mode=login&sid=616...       0
2568181                                  http://ltmagox.ru       1
2568182               http://morgane-clara.blogspot.com.es       1
2568183                 http://spankersview.blogspot.co.za       1

[2568184 rows x 2 columns]

In [53]:
df = pd.concat([df1,df2], axis = 0).reset_index(drop = True)

In [54]:
df = df.sample(frac = 1).reset_index(drop = True)

In [55]:
df.shape

(2624526, 2)

In [56]:
df.to_csv('Final_Test.csv')