In [4]:
import pandas as pd
import numpy as np

In [5]:
import requests

In [6]:
from bs4 import BeautifulSoup

In [7]:
import lxml

In [8]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Connection": "keep-alive"
}

url = "https://www.phishtank.com/phish_search.php?page=1&valid=y&Search=Search"

response = requests.get(url, headers=headers)

ConnectionError: HTTPSConnectionPool(host='www.phishtank.com', port=443): Max retries exceeded with url: /phish_search.php?page=1&valid=y&Search=Search (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E1E03F5D30>: Failed to resolve 'www.phishtank.com' ([Errno 11001] getaddrinfo failed)"))

In [9]:
webpage

NameError: name 'webpage' is not defined

In [10]:
if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
else:
    print(response.status_code)

NameError: name 'response' is not defined

In [ ]:
api_key = "YOUR_API_KEY"
url_to_check = "https://www.phishtank.com/phish_search.php?page=1&valid=y&Search=Search"
api_url = "https://checkurl.phishtank.com/checkurl/"
data = {
    "url": url_to_check,
    "format": "json",
    "app_key": api_key
}
response = requests.post(api_url, data=data)
if response.status_code == 200:
    result = response.json()
    print(result)
else:
    print(response.status_code)

In [11]:
import requests
url = "http://data.phishtank.com/data/online-valid.json"
response = requests.get(url)
if response.status_code == 200:
    with open("online-valid.json", "wb") as f:
        f.write(response.content)
    print("ds")
else:
    print("Error:", response.status_code)

ConnectionError: HTTPConnectionPool(host='data.phishtank.com', port=80): Max retries exceeded with url: /data/online-valid.json (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001E1E03F6900>: Failed to resolve 'data.phishtank.com' ([Errno 11001] getaddrinfo failed)"))

In [12]:
import json
with open("online-valid.json", "r", encoding="utf-8") as f:
    data = json.load(f)

In [13]:
data

[{'phish_id': 9340837,
  'url': 'https://allegrolokalnie.oferta736173-kategoria-proponowane.sbs/',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340837',
  'submission_time': '2026-02-11T14:09:44+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T14:12:37+00:00',
  'online': 'yes',
  'details': [],
  'target': 'Allegro'},
 {'phish_id': 9340823,
  'url': 'https://allegrolokalnie.56kbkdcnn3v.sbs/',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340823',
  'submission_time': '2026-02-11T13:50:15+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:53:39+00:00',
  'online': 'yes',
  'details': [],
  'target': 'Allegro'},
 {'phish_id': 9340822,
  'url': 'https://allegrolokalnie.btkr3rfdsnc4br.sbs/',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340822',
  'submission_time': '2026-02-11T13:50:01+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:53:39+00:00',
  'online': 'yes',
  'details': [{'ip_address': '104.21.71.159',
    'cidr_block': '104.21.64.0/19',
    'announcing_network': '13335',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T13:52:58+00:00'}],
  'target': 'Allegro'},
 {'phish_id': 9340821,
  'url': 'https://lobpatoppen.dk/united/g.html.html',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340821',
  'submission_time': '2026-02-11T13:47:57+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:53:39+00:00',
  'online': 'yes',
  'details': [{'ip_address': '91.208.75.16',
    'cidr_block': '91.208.75.0/24',
    'announcing_network': '6718',
    'rir': 'ripencc',
    'country': 'RO',
    'detail_time': '2026-02-11T13:52:58+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340820,
  'url': 'https://dayszorg.nl/ac7162df752d24ee43f300c12c556b5f/AreaUtenti_Lang.php?servizio=TW96aWxsYS81LjAgKExpbnV4OyBBbmRyb2lkIDE1KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTM1LjAuNzA0OS45NSBNb2JpbGUgU2FmYXJpLzUzNy4zNjgxLjU3LjExMi4xNjEyMDI2OkZlYjpXZWQ=',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340820',
  'submission_time': '2026-02-11T13:40:25+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:53:39+00:00',
  'online': 'yes',
  'details': [{'ip_address': '85.214.213.173',
    'cidr_block': '85.214.0.0/15',
    'announcing_network': '6724',
    'rir': 'ripencc',
    'country': 'DE',
    'detail_time': '2026-02-11T13:52:57+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340801,
  'url': 'https://www.pl-8726192123.icu/',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340801',
  'submission_time': '2026-02-11T13:30:22+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:42:36+00:00',
  'online': 'yes',
  'details': [{'ip_address': '109.107.189.111',
    'cidr_block': '109.107.189.0/24',
    'announcing_network': '216246',
    'rir': 'ripencc',
    'country': 'RU',
    'detail_time': '2026-02-11T13:52:57+00:00'}],
  'target': 'Allegro'},
 {'phish_id': 9340799,
  'url': 'http://olx.pl-12677.sbs',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340799',
  'submission_time': '2026-02-11T13:30:15+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:42:36+00:00',
  'online': 'yes',
  'details': [{'ip_address': '104.21.0.220',
    'cidr_block': '104.21.0.0/19',
    'announcing_network': '13335',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T13:52:57+00:00'}],
  'target': 'Allegro'},
 {'phish_id': 9340797,
  'url': 'https://allegrolokalnie.pl-smart97587125.cfd/oferta/24821291/karta-graficzna-msi-rtx-3060-ti-gaming-x-8g-lhr',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340797',
  'submission_time': '2026-02-11T13:29:55+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:32:40+00:00',
  'online': 'yes',
  'details': [{'ip_address': '172.67.130.187',
    'cidr_block': '172.67.128.0/20',
    'announcing_network': '13335',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T13:33:00+00:00'}],
  'target': 'Allegro'},
 {'phish_id': 9340788,
  'url': 'https://sahayagiri.org/ions',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340788',
  'submission_time': '2026-02-11T13:22:09+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:32:40+00:00',
  'online': 'yes',
  'details': [{'ip_address': '209.133.204.250',
    'cidr_block': '209.133.192.0/19',
    'announcing_network': '29802',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T13:33:00+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340787,
  'url': 'https://myansmed.com/ions/',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340787',
  'submission_time': '2026-02-11T13:21:15+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:32:40+00:00',
  'online': 'yes',
  'details': [{'ip_address': '198.54.115.171',
    'cidr_block': '198.54.112.0/20',
    'announcing_network': '22612',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T13:33:00+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340779,
  'url': 'https://webtrust.created.app',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340779',
  'submission_time': '2026-02-11T13:09:33+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:12:45+00:00',
  'online': 'yes',
  'details': [{'ip_address': '216.150.1.129',
    'cidr_block': '216.150.1.0/24',
    'announcing_network': '16509',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T13:13:00+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340778,
  'url': 'https://engstart.ghost.io/exodus-hub',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340778',
  'submission_time': '2026-02-11T13:09:31+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:12:45+00:00',
  'online': 'yes',
  'details': [{'ip_address': '146.75.35.7',
    'cidr_block': '146.75.32.0/22',
    'announcing_network': '54113',
    'rir': 'ripencc',
    'country': 'US',
    'detail_time': '2026-02-11T13:12:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340775,
  'url': 'https://docs-exed-us-web3.pages.dev',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340775',
  'submission_time': '2026-02-11T13:08:32+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:12:45+00:00',
  'online': 'yes',
  'details': [{'ip_address': '172.66.44.212',
    'cidr_block': '172.66.40.0/21',
    'announcing_network': '13335',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T13:12:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340774,
  'url': 'https://us-exodus-docs.pages.dev',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340774',
  'submission_time': '2026-02-11T13:08:04+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:12:45+00:00',
  'online': 'yes',
  'details': [{'ip_address': '172.66.47.152',
    'cidr_block': '172.66.40.0/21',
    'announcing_network': '13335',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T13:12:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340773,
  'url': 'https://xeoduswv3.gitbook.io/us',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340773',
  'submission_time': '2026-02-11T13:07:36+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:12:45+00:00',
  'online': 'yes',
  'details': [{'ip_address': '172.64.147.209',
    'cidr_block': '172.64.147.0/24',
    'announcing_network': '13335',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T13:12:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340772,
  'url': 'https://exo-dus.framer.media',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340772',
  'submission_time': '2026-02-11T13:07:07+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:12:45+00:00',
  'online': 'yes',
  'details': [{'ip_address': '35.71.142.77',
    'cidr_block': '35.71.128.0/20',
    'announcing_network': '16509',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T13:12:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340771,
  'url': 'https://exodus-web3-wallet-auth.created.app',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340771',
  'submission_time': '2026-02-11T13:06:38+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:12:45+00:00',
  'online': 'yes',
  'details': [{'ip_address': '216.150.1.193',
    'cidr_block': '216.150.1.0/24',
    'announcing_network': '16509',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T13:12:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340769,
  'url': 'https://starts-home.ghost.io/exodus',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340769',
  'submission_time': '2026-02-11T13:06:07+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:12:45+00:00',
  'online': 'yes',
  'details': [{'ip_address': '146.75.35.7',
    'cidr_block': '146.75.32.0/22',
    'announcing_network': '54113',
    'rir': 'ripencc',
    'country': 'US',
    'detail_time': '2026-02-11T13:12:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340761,
  'url': 'https://ipfs.io/ipfs/bafkreibx2p5dymfxvio2mn4jj3pysg7gkd2px5hyixmrbr2kc2no7qza3i/#a@b.com',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340761',
  'submission_time': '2026-02-11T12:55:42+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:12:45+00:00',
  'online': 'yes',
  'details': [{'ip_address': '209.94.90.1',
    'cidr_block': '209.94.90.0/24',
    'announcing_network': '40680',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T13:12:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340756,
  'url': 'https://webapp-ar24.catifueblowe.icu/',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340756',
  'submission_time': '2026-02-11T12:53:32+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T13:03:25+00:00',
  'online': 'yes',
  'details': [{'ip_address': '172.67.145.18',
    'cidr_block': '172.67.144.0/20',
    'announcing_network': '13335',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T13:12:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340734,
  'url': 'https://lavender-aardvark-717923.hostingersite.com/',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340734',
  'submission_time': '2026-02-11T12:38:51+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:42:39+00:00',
  'online': 'yes',
  'details': [{'ip_address': '191.96.144.75',
    'cidr_block': '191.96.144.0/24',
    'announcing_network': '47583',
    'rir': 'ripencc',
    'country': 'AE',
    'detail_time': '2026-02-11T12:53:00+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340727,
  'url': 'https://intranet.universe.us/fiene/Neimi/login.php',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340727',
  'submission_time': '2026-02-11T12:30:47+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:42:39+00:00',
  'online': 'yes',
  'details': [{'ip_address': '74.208.252.249',
    'cidr_block': '74.208.0.0/16',
    'announcing_network': '8560',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T12:52:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340728,
  'url': 'https://dkbkontaktinformationen1.sviluppo.host/on/content/notice.php',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340728',
  'submission_time': '2026-02-11T12:30:47+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:42:39+00:00',
  'online': 'yes',
  'details': [{'ip_address': '149.62.188.254',
    'cidr_block': '149.62.188.0/24',
    'announcing_network': '47242',
    'rir': 'ripencc',
    'country': 'IT',
    'detail_time': '2026-02-11T12:52:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340724,
  'url': 'https://dkbkontaktinformationen1.sviluppo.host/on/content/push.php',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340724',
  'submission_time': '2026-02-11T12:30:46+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:42:39+00:00',
  'online': 'yes',
  'details': [{'ip_address': '149.62.188.254',
    'cidr_block': '149.62.188.0/24',
    'announcing_network': '47242',
    'rir': 'ripencc',
    'country': 'IT',
    'detail_time': '2026-02-11T12:52:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340725,
  'url': 'https://dkbkontaktinformationen1.sviluppo.host/on/content/login.php?client_ID=b204858q36z778j15156566973971x0f&session_ID=v185ha0t1h64o43',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340725',
  'submission_time': '2026-02-11T12:30:46+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:42:39+00:00',
  'online': 'yes',
  'details': [{'ip_address': '149.62.188.254',
    'cidr_block': '149.62.188.0/24',
    'announcing_network': '47242',
    'rir': 'ripencc',
    'country': 'IT',
    'detail_time': '2026-02-11T12:52:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340726,
  'url': 'https://dkbkontaktinformationen1.sviluppo.host/on/content/sms.php',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340726',
  'submission_time': '2026-02-11T12:30:46+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:42:39+00:00',
  'online': 'yes',
  'details': [{'ip_address': '149.62.188.254',
    'cidr_block': '149.62.188.0/24',
    'announcing_network': '47242',
    'rir': 'ripencc',
    'country': 'IT',
    'detail_time': '2026-02-11T12:52:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340722,
  'url': 'https://dkbkontaktinformationen1.sviluppo.host/on/content/login.php',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340722',
  'submission_time': '2026-02-11T12:30:12+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:42:39+00:00',
  'online': 'yes',
  'details': [{'ip_address': '149.62.188.254',
    'cidr_block': '149.62.188.0/24',
    'announcing_network': '47242',
    'rir': 'ripencc',
    'country': 'IT',
    'detail_time': '2026-02-11T12:52:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340721,
  'url': 'https://dkbkontaktinformationen1.sviluppo.host/on/content/finish.php',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340721',
  'submission_time': '2026-02-11T12:30:11+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:42:39+00:00',
  'online': 'yes',
  'details': [{'ip_address': '149.62.188.254',
    'cidr_block': '149.62.188.0/24',
    'announcing_network': '47242',
    'rir': 'ripencc',
    'country': 'IT',
    'detail_time': '2026-02-11T12:52:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340719,
  'url': 'https://dkbkontaktinformationen1.sviluppo.host/on/content/email.php',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340719',
  'submission_time': '2026-02-11T12:30:10+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:42:39+00:00',
  'online': 'yes',
  'details': [{'ip_address': '149.62.188.254',
    'cidr_block': '149.62.188.0/24',
    'announcing_network': '47242',
    'rir': 'ripencc',
    'country': 'IT',
    'detail_time': '2026-02-11T12:52:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340720,
  'url': 'https://dkbkontaktinformationen1.sviluppo.host/on/content/failed.php',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340720',
  'submission_time': '2026-02-11T12:30:10+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:42:39+00:00',
  'online': 'yes',
  'details': [{'ip_address': '149.62.188.254',
    'cidr_block': '149.62.188.0/24',
    'announcing_network': '47242',
    'rir': 'ripencc',
    'country': 'IT',
    'detail_time': '2026-02-11T12:52:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340717,
  'url': 'https://dkbkontaktinformationen1.sviluppo.host/on/content/cc.php',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340717',
  'submission_time': '2026-02-11T12:30:08+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:42:39+00:00',
  'online': 'yes',
  'details': [{'ip_address': '149.62.188.254',
    'cidr_block': '149.62.188.0/24',
    'announcing_network': '47242',
    'rir': 'ripencc',
    'country': 'IT',
    'detail_time': '2026-02-11T12:52:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340718,
  'url': 'https://dkbkontaktinformationen1.sviluppo.host/on/content/agreement.php',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340718',
  'submission_time': '2026-02-11T12:30:08+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:42:39+00:00',
  'online': 'yes',
  'details': [{'ip_address': '149.62.188.254',
    'cidr_block': '149.62.188.0/24',
    'announcing_network': '47242',
    'rir': 'ripencc',
    'country': 'IT',
    'detail_time': '2026-02-11T12:52:59+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340711,
  'url': 'http://allegrolokalnie.pl-09162.sbs',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340711',
  'submission_time': '2026-02-11T12:24:21+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:32:42+00:00',
  'online': 'yes',
  'details': [{'ip_address': '172.67.206.115',
    'cidr_block': '172.67.192.0/20',
    'announcing_network': '13335',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T12:33:05+00:00'}],
  'target': 'Allegro'},
 {'phish_id': 9340705,
  'url': 'http://allegrolokalnie.pl-09162.sbs/',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340705',
  'submission_time': '2026-02-11T12:19:50+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:32:42+00:00',
  'online': 'yes',
  'details': [{'ip_address': '172.67.206.115',
    'cidr_block': '172.67.192.0/20',
    'announcing_network': '13335',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T12:33:05+00:00'}],
  'target': 'Allegro'},
 {'phish_id': 9340696,
  'url': 'https://82jw5w.lat/0njqo6ge/JkosKq/beZCTg',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340696',
  'submission_time': '2026-02-11T12:12:02+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:22:14+00:00',
  'online': 'yes',
  'details': [{'ip_address': '172.67.134.165',
    'cidr_block': '172.67.128.0/20',
    'announcing_network': '13335',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T12:33:05+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340693,
  'url': 'https://82j7he.lat/0njqo6ge/JkosKq/beZCTg',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340693',
  'submission_time': '2026-02-11T12:10:02+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:22:14+00:00',
  'online': 'yes',
  'details': [{'ip_address': '104.21.71.97',
    'cidr_block': '104.21.64.0/20',
    'announcing_network': '13335',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T12:33:05+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340690,
  'url': 'https://82hwgf3.lat/0njqo6ge/JkosKq/beZCTg',
  'phish_detail_url': 'http://www.phishtank.com/phish_detail.php?phish_id=9340690',
  'submission_time': '2026-02-11T12:08:02+00:00',
  'verified': 'yes',
  'verification_time': '2026-02-11T12:22:14+00:00',
  'online': 'yes',
  'details': [{'ip_address': '104.21.0.93',
    'cidr_block': '104.21.0.0/20',
    'announcing_network': '13335',
    'rir': 'arin',
    'country': 'US',
    'detail_time': '2026-02-11T12:33:05+00:00'}],
  'target': 'Other'},
 {'phish_id': 9340688,

In [14]:
df1 = pd.DataFrame(data)

In [16]:
df1.sample(50)

,phish_id,url,phish_detail_url,submission_time,verified,verification_time,online,details,target
36990,8680856,https://l.ead.me/bfGEyL,http://www.phishtank.com/phish_detail.php?phis...,2024-07-27T00:58:15+00:00,yes,2024-07-27T01:04:26+00:00,yes,"[{'ip_address': '18.160.10.92', 'cidr_block': ...",Other
7257,9326221,https://q-r.to/bgaOie,http://www.phishtank.com/phish_detail.php?phis...,2026-01-29T16:52:32+00:00,yes,2026-01-29T17:21:47+00:00,yes,"[{'ip_address': '18.160.10.52', 'cidr_block': ...",Other
32598,8742138,https://docs.google.com/presentation/d/1JCkDlC...,http://www.phishtank.com/phish_detail.php?phis...,2024-09-03T16:21:28+00:00,yes,2024-09-03T16:22:54+00:00,yes,"[{'ip_address': '142.251.167.102', 'cidr_block...",Other
28604,8836922,https://docs.google.com/presentation/d/e/2PACX...,http://www.phishtank.com/phish_detail.php?phis...,2024-11-06T17:36:40+00:00,yes,2024-11-06T17:42:03+00:00,yes,"[{'ip_address': '64.233.180.138', 'cidr_block'...",Other
26497,8906344,https://shine-s-school4.teachable.com/p/yahoo,http://www.phishtank.com/phish_detail.php?phis...,2024-12-17T21:51:17+00:00,yes,2024-12-17T22:03:01+00:00,yes,"[{'ip_address': '104.17.83.54', 'cidr_block': ...",Other
11020,9316623,https://qrco.de/bgZaIO,http://www.phishtank.com/phish_detail.php?phis...,2026-01-21T11:09:11+00:00,yes,2026-01-21T11:21:41+00:00,yes,"[{'ip_address': '18.160.10.92', 'cidr_block': ...",Other
42723,8484022,https://eximiamedical.ro/,http://www.phishtank.com/phish_detail.php?phis...,2024-03-08T20:57:25+00:00,yes,2024-03-08T21:12:55+00:00,yes,"[{'ip_address': '104.26.10.126', 'cidr_block':...",Other
32207,8748746,https://docs.google.com/presentation/d/1l4di5q...,http://www.phishtank.com/phish_detail.php?phis...,2024-09-07T21:31:22+00:00,yes,2024-09-07T21:33:16+00:00,yes,"[{'ip_address': '64.233.180.101', 'cidr_block'...",Other
41497,8539708,https://pub-dfa124c0bc8f4f30bb3bb755962d3838.r...,http://www.phishtank.com/phish_detail.php?phis...,2024-04-16T21:50:38+00:00,yes,2024-04-16T21:53:00+00:00,yes,"[{'ip_address': '104.18.3.35', 'cidr_block': '...",Other
163,9340473,https://webmailthemessagiingcocomau.weebly.com/,http://www.phishtank.com/phish_detail.php?phis...,2026-02-11T05:00:06+00:00,yes,2026-02-11T05:12:33+00:00,yes,"[{'ip_address': '74.115.51.8', 'cidr_block': '...",Other
13861,9284562,https://app.bia-resolve.digital,http://www.phishtank.com/phish_detail.php?phis...,2025-12-05T22:26:16+00:00,yes,2025-12-05T22:32:09+00:00,yes,"[{'ip_address': '172.67.163.89', 'cidr_block':...",Other
4462,9332224,https://www.yamamotozu.com/web/login,http://www.phishtank.com/phish_detail.php?phis...,2026-02-04T05:36:19+00:00,yes,2026-02-04T05:42:05+00:00,yes,"[{'ip_address': '158.51.96.37', 'cidr_block': ...",American Express
8837,9322629,https://www.boursobank-service-annulation.com/,http://www.phishtank.com/phish_detail.php?phis...,2026-01-27T08:28:44+00:00,yes,2026-01-27T08:32:34+00:00,yes,"[{'ip_address': '45.74.47.19', 'cidr_block': '...",Other
24253,9023837,https://docs.google.com/presentation/d/e/2PACX...,http://www.phishtank.com/phish_detail.php?phis...,2025-03-18T02:50:50+00:00,yes,2025-03-18T03:02:59+00:00,yes,"[{'ip_address': '172.253.122.113', 'cidr_block...",Other
26731,8897060,https://flow.page/ho394,http://www.phishtank.com/phish_detail.php?phis...,2024-12-11T14:28:05+00:00,yes,2024-12-11T14:32:26+00:00,yes,"[{'ip_address': '104.18.41.197', 'cidr_block':...",Other
2475,9335970,https://l.ead.me/bgbfnD,http://www.phishtank.com/phish_detail.php?phis...,2026-02-07T01:14:28+00:00,yes,2026-02-07T01:52:23+00:00,yes,"[{'ip_address': '18.160.10.24', 'cidr_block': ...",Other
13478,9292695,https://ovhfrance.com/FR658E5F2EZ560000/FR2025...,http://www.phishtank.com/phish_detail.php?phis...,2025-12-17T16:13:46+00:00,yes,2025-12-17T16:32:24+00:00,yes,"[{'ip_address': '103.179.189.95', 'cidr_block'...",Other
50715,8126646,https://ipfs.best-practice.se/ipfs/bafybeifrt2...,http://www.phishtank.com/phish_detail.php?phis...,2023-04-24T04:46:47+00:00,yes,2023-04-24T05:17:33+00:00,yes,"[{'ip_address': '193.11.118.5', 'cidr_block': ...",Other
43002,8472876,https://rp.mockplus.com/run/5QLSj5KQpn/1-Z7Kvn...,http://www.phishtank.com/phish_detail.php?phis...,2024-03-01T19:19:57+00:00,yes,2024-03-01T19:42:35+00:00,yes,"[{'ip_address': '47.253.49.17', 'cidr_block': ...",Other
31019,8771341,https://sites.google.com/view/876799/home,http://www.phishtank.com/phish_detail.php?phis...,2024-09-20T13:26:34+00:00,yes,2024-09-20T13:33:39+00:00,yes,"[{'ip_address': '172.253.115.101', 'cidr_block...",Other
48785,8259951,https://orango-lado.firebaseapp.com/,http://www.phishtank.com/phish_detail.php?phis...,2023-08-14T23:21:24+00:00,yes,2023-08-14T23:42:06+00:00,yes,"[{'ip_address': '199.36.158.100', 'cidr_block'...",Other
49738,8194483,https://yvuybnuo.firebaseapp.com/,http://www.phishtank.com/phish_detail.php?phis...,2023-06-24T07:33:58+00:00,yes,2023-06-24T08:23:04+00:00,yes,"[{'ip_address': '199.36.158.100', 'cidr_block'...",Other
6210,9328393,https://q-r.to/bgamZA,http://www.phishtank.com/phish_detail.php?phis...,2026-01-31T12:08:06+00:00,yes,2026-01-31T13:03:11+00:00,yes,"[{'ip_address': '18.160.10.52', 'cidr_block': ...",Other
5345,9330466,https://lovable-adapts-576181.framer.app/,http://www.phishtank.com/phish_detail.php?phis...,2026-02-02T19:36:03+00:00,yes,2026-02-02T20:41:56+00:00,yes,"[{'ip_address': '35.71.142.77', 'cidr_block': ...",Other
20368,9156710,https://app.jotform.com/251754496265568,http://www.phishtank.com/phish_detail.php?phis...,2025-07-16T09:41:37+00:00,yes,2025-07-16T09:52:36+00:00,yes,"[{'ip_address': '104.18.24.107', 'cidr_block':...",Other
36509,8689605,https://l.ead.me/bfGlkC,http://www.phishtank.com/phish_detail.php?phis...,2024-08-01T12:25:41+00:00,yes,2024-08-01T12:33:10+00:00,yes,"[{'ip_address': '18.160.10.113', 'cidr_block':...",Other
15424,9254816,https://gemincxologin.gitbook.io/us/,http://www.phishtank.com/phish_detail.php?phis...,2025-10-30T17:55:46+00:00,yes,2025-10-30T18:03:00+00:00,yes,"[{'ip_address': '172.64.147.209', 'cidr_block'...",Other
29301,8811580,https://q-r.to/bfTeZG,http://www.phishtank.com/phish_detail.php?phis...,2024-10-18T01:10:09+00:00,yes,2024-10-18T01:11:48+00:00,yes,"[{'ip_address': '18.160.10.113', 'cidr_block':...",Other
36143,8696578,https://qrco.de/bfHZwD,http://www.phishtank.com/phish_detail.php?phis...,2024-08-05T16:04:05+00:00,yes,2024-08-05T16:23:28+00:00,yes,"[{'ip_address': '18.160.10.52', 'cidr_block': ...",Other
10636,9317890,https://blockchnelogen.gitbook.io/usa/,http://www.phishtank.com/phish_detail.php?phis...,2026-01-22T12:19:35+00:00,yes,2026-01-22T12:32:33+00:00,yes,"[{'ip_address': '172.64.147.209', 'cidr_block'...",Other
44594,8426292,https://sweepstakes630.godaddysites.com/,http://www.phishtank.com/phish_detail.php?phis...,2024-01-24T08:45:19+00:00,yes,2024-01-24T08:53:22+00:00,yes,"[{'ip_address': '76.223.105.230', 'cidr_block'...","eBay, Inc."
8600,9323140,https://started-m.ghost.io/en-exodus/,http://www.phishtank.com/phish_detail.php?phis...,2026-01-27T14:03:03+00:00,yes,2026-01-27T14:12:05+00:00,yes,"[{'ip_address': '146.75.39.7', 'cidr_block': '...",Other
50070,8161404,http://tiny.cc/rwk7vz,http://www.phishtank.com/phish_detail.php?phis...,2023-05-31T19:37:51+00:00,yes,2023-05-31T20:04:20+00:00,yes,"[{'ip_address': '157.245.113.153', 'cidr_block...",Other
41463,8541488,https://docs.google.com/presentation/d/e/2PACX...,http://www.phishtank.com/phish_detail.php?phis...,2024-04-18T04:16:45+00:00,yes,2024-04-18T04:23:29+00:00,yes,"[{'ip_address': '142.251.167.139', 'cidr_block...",Other
33184,8731395,https://q-r.to/bfKx0P,http://www.phishtank.com/phish_detail.php?phis...,2024-08-25T15:23:54+00:00,yes,2024-08-25T15:33:29+00:00,yes,"[{'ip_address': '18.160.10.52', 'cidr_block': ...",Other
41019,8561415,https://www.dropbox.com/scl/fi/srzpd0q5qgoiqdv...,http://www.phishtank.com/phish_detail.php?phis...,2024-05-02T17:22:00+00:00,yes,2024-05-02T17:33:16+00:00,yes,"[{'ip_address': '162.125.6.18', 'cidr_block': ...",Other
38250,8655270,https://shaw-107237.square.site/,http://www.phishtank.com/phish_detail.php?phis...,2024-07-14T16:29:53+00:00,yes,2024-07-14T16:43:11+00:00,yes,"[{'ip_address': '74.115.51.4', 'cidr_block': '...",Other
3264,9334607,https://wwwinstagramlogin-com.github.io/Instag...,http://www.phishtank.com/phish_detail.php?phis...,2026-02-05T21:22:36+00:00,yes,2026-02-05T22:03:07+00:00,yes,"[{'ip_address': '185.199.111.153', 'cidr_block...",Other
1504,9337789,https://q-r.to/bgbdJc,http://www.phishtank.com/phish_detail.php?phis...,2026-02-08T21:18:51+00:00,yes,2026-02-08T22:42:11+00:00,yes,"[{'ip_address': '18.160.10.113', 'cidr_block':...",Other
36512,8689599,https://l.ead.me/bfGvoR,http://www.phishtank.com/phish_detail.php?phis...,2024-08-01T12:24:50+00:00,yes,2024-08-01T12:33:11+00:00,yes,"[{'ip_address': '18.160.10.113', 'cidr_block':...",Other
28385,8842218,https://l.ead.me/bfY0rq,http://www.phishtank.com/phish_detail.php?phis...,2024-11-09T13:18:04+00:00,yes,2024-11-09T13:32:05+00:00,yes,"[{'ip_address': '18.160.10.113', 'cidr_block':...",Other
53652,7489166,http://azuki-110716005.vercel.app,http://www.phishtank.com/phish_detail.php?phis...,2022-04-15T05:50:32+00:00,yes,2022-04-15T11:52:05+00:00,yes,"[{'ip_address': '76.223.121.104', 'cidr_block'...",Other
49383,8223467,https://rasunalo20.firebaseapp.com/,http://www.phishtank.com/phish_detail.php?phis...,2023-07-13T23:26:05+00:00,yes,2023-07-13T23:31:44+00:00,yes,"[{'ip_address': '199.36.158.100', 'cidr_block'...",Other
53744,7421604,https://altecmetalltechnik-energiasolar.blogsp...,http://www.phishtank.com/phish_detail.php?phis...,2022-01-24T14:12:01+00:00,yes,2022-02-23T03:56:21+00:00,yes,"[{'ip_address': '142.250.188.193', 'cidr_block...",Other
39398,8618427,https://tapk.it/attt010,http://www.phishtank.com/phish_detail.php?phis...,2024-06-17T14:28:33+00:00,yes,2024-06-17T14:33:59+00:00,yes,"[{'ip_address': '199.36.158.100', 'cidr_block'...",Other
45143,8406158,https://new.express.adobe.com/webpage/nSu6pV0W...,http://www.phishtank.com/phish_detail.php?phis...,2023-12-29T04:38:13+00:00,yes,2023-12-29T04:43:10+00:00,yes,"[{'ip_address': '99.84.208.112', 'cidr_block':...",Other
31366,8760568,https://docs.google.com/presentation/d/196xEmr...,http://www.phishtank.com/phish_detail.php?phis...,2024-09-14T23:01:42+00:00,yes,2024-09-14T23:09:20+00:00,yes,"[{'ip_address': '172.253.115.138', 'cidr_block...",Other
28228,8847161,https://docs.google.com/presentation/d/e/2PACX...,http://www.phishtank.com/phish_detail.php?phis...,2024-11-12T00:11:31+00:00,yes,2024-11-12T00:12:19+00:00,yes,"[{'ip_address': '142.251.16.100', 'cidr_block'...",Other
40856,8567254,https://docs.google.com/presentation/d/e/2PACX...,http://www.phishtank.com/phish_detail.php?phis...,2024-05-07T19:52:30+00:00,yes,2024-05-07T20:03:36+00:00,yes,"[{'ip_address': '142.251.163.139', 'cidr_block...",Other
25351,8957862,https://docs.google.com/presentation/d/e/2PACX...,http://www.phishtank.com/phish_detail.php?phis...,2025-01-30T21:01:49+00:00,yes,2025-01-30T21:12:37+00:00,yes,"[{'ip_address': '142.251.167.101', 'cidr_block...",Other

In [17]:
with open("malign_Train.txt", "r", encoding="utf-8") as f:
    urls = f.read().splitlines()
df2 = pd.DataFrame(urls, columns=["url"])
df2['Phish?'] = 1

In [18]:
df2.shape

(2000000, 2)

In [19]:
with open("benign_Train.txt", "r", encoding="utf-8") as f:
    urls = f.read().splitlines()
df3 = pd.DataFrame(urls, columns=["url"])
df3['Phish?'] = 0

In [20]:
df3.shape

(2000000, 2)

In [29]:
with open("benign_Test.txt", "r", encoding="utf-8") as f:
    urls = f.read().splitlines()
df4 = pd.DataFrame(urls, columns=["url"])
df5['Phish?'] = 0

In [30]:
df4.shape

(1087717, 1)

In [31]:
with open("malign_Test.txt", "r", encoding="utf-8") as f:
    urls = f.read().splitlines()
df5 = pd.DataFrame(urls, columns=["url"])
df5['Phish?'] = 1

In [32]:
df5.shape

(1480467, 2)

In [33]:
Train = pd.concat([df3, df2], ignore_index=True, )

In [34]:
Train

                                                       url  Phish?
0                   karens-krazy-korner.blogspot.com/2010/       0
1          www.tmentertainment.com/ccount/click.php?id=173       0
2        asian.videos.xblog.in/thai-wife-get-fuck-by-hu...       0
3                     kpn.se/resurser/bilder-att-farglagga       0
4           www.indokitay.ru/landing/toniki-aasha-herbals/       0
...                                                    ...     ...
3999995                                  pd-de.as.pptv.com       1
3999996                                         spanku.com       1
3999997  mapharma.fr/errors/default/browser-detection/f...       1
3999998                          cokeandnitrus.blogspot.my       1
3999999                           quesobon.blogspot.com.ee       1

[4000000 rows x 2 columns]

In [35]:
Train = Train.sample(frac=1).reset_index(drop=True)

In [36]:
Train

                                                       url  Phish?
0        www.musik-glanzmann.ch/product-page/paiste-sig...       0
1                                  kinkydangle.blogspot.ae       1
2                           fukuchan.net/publics/index/32/       0
3                            gaypornstorage.blogspot.co.at       1
4        herecomestheguide.com/southern-california/wedd...       1
...                                                    ...     ...
3999995    hakusakublog.blog86.fc2.com/blog-entry-531.html       0
3999996                                 www.xyzscripts.com       1
3999997                            cumandgetit.blogspot.al       1
3999998  www.sbdmtr.cz/index.php?option=com_content&vie...       0
3999999  opac.sbn.it/opacsbn/opaclib?rpnlabel=+bid+%3d+...       0

[4000000 rows x 2 columns]

In [37]:
Test = pd.concat([df5, df4], ignore_index=True, )

In [38]:
Test = Test.sample(frac=1).reset_index(drop=True)

In [39]:
Train.to_csv('Train.csv')

In [40]:
Test.to_csv('Test.csv')

In [43]:
Test.sample(frac = 1).reset_index(drop = True)

                                                       url  Phish?
0                                          www.callcid.com     1.0
1                                       kms.nanonation.net     1.0
2        kochen.gofeminin.de/rezepte/rezept_gemuse-crem...     NaN
3                                 xaviertoutnu.blogspot.gr     1.0
4                              hotmoviesforyou.blogspot.gr     1.0
...                                                    ...     ...
2568179               www.osotir.org/2013/08/01/2-2013-25/     NaN
2568180                          bondage-fotos.blogspot.al     1.0
2568181                           www.favfamilyrecipes.com     1.0
2568182                              deliciousdesserts.net     1.0
2568183                        hellozipcodes.com/fl/32833/     NaN

[2568184 rows x 2 columns]